language: python
python:
  - 3.8.5

services:
  - docker

install:
  - docker --version
  - pip install pipenv

before_script:
  - pipenv install --dev
  - sudo service postgresql stop

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - source setup_dev_env.sh
  - sh run_tests.sh

after_success:
  - coveralls

notifications:
  email: false

env:
  jobs:
    - CRATE_VERSION=4.1.4 QL_PREV_IMAGE=smartsdk/quantumleap:0.8 PREV_CRATE=4.0.12
